### PR TITLE
Add Py_IsFinalizing()

### PR DESCRIPTION
**Pull request by vstinner**

### CODE REVIEW

**Comment by vstinner** [comment]
PR waiting until https://github.com/python/cpython/pull/108032 is merged in Python upstream.

**Comment by albanD** [comment]
Hey!

I have a related question but it is not 100% about this PR so feel free to delete if you think this is not the right place to ask.

There have been quite a few discussions related to `Py_IsFinalizing` and `Py_Initialized` and how to use them to ensure graceful exit when c++ keeps things alive past python runtime lifetime.
https://github.com/pytorch/pytorch/blob/589072afa1a196270b0298460c1f419e209da6ea/torch/csrc/utils/pybind.h#L178-L185

Is this comment still accurate for the latest version of CPython? Should we update our use of these functions to use the new public API being introduced?

**Comment by vstinner** [comment]
> Is this comment still accurate for the latest version of CPython?

I don't know. This PR is on the pythoncapi-compat project, not the Python project.

**Review by erlend-aasland — APPROVED** [review]

**Comment by vstinner** [comment]
I dug into PyPy tarball releases to check which version added Py_IsFinalizing(): it's PyPy 7.3. Sadly, on GitHub Actions we only tests versions newer than PyPy 7.3.0: PyPy 7.2 and older are not tested.

**Pull request merged**
